# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
MEMORY = 2048

PRIVATE_IP = ENV['VAGRANT_PRIVATE_IP'] || '192.168.33.15'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: PRIVATE_IP
  config.vm.synced_folder  ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
  end

  if not ENV['VAGRANT_NO_PORTS']
    config.vm.network :forwarded_port, guest: 8080, host: 8080  # Jenkins
  end

   config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../../playbooks/analytis-jenkins.yml"
    # ansible.verbose = "vvvv"

    ansible.extra_vars = {}
  end

end
